name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 您的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # 如果需要，添加执行权限（可选）
      - name: Add execute permissions to vitepress
        run: chmod +x ./node_modules/.bin/vitepress

      - name: Build project
        # 使用 npx 确保找到本地安装的 vitepress
        run: npx vitepress build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './dist'
